apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo

resources:
  # Create namespace first
  - namespace.yaml
  # Argo Workflow install manifest
  - https://github.com/argoproj/argo-workflows/releases/download/v3.5.11/install.yaml
